### PR TITLE
Simplified test

### PR DESCRIPTION
**Pull request by pfichtner**
I didn't understand why the cell value is "0, 1". Actually, a bingo cell should only contain numbers, possibly also letters. In order not to make the code too complex, I have dispensed with further checks. 

The API could possibly be
`void defineCell(int x, int y, Integer value)`
would be better or clearer (but more restricted) than
`void defineCell(int x, int y, String value)`

Was "0, 1" intentional or a misinterpretation of the API? Should I change the API in the Java and C# code to take an Integer as parameter?

### CODE REVIEW

**Comment by emilybache** [comment]
I think the sample test data is there to make it easier to get a good error message when a test fails, it's not supposed to be an example of what realistic data would look like in production.  I prefer an interface that lets the Bingo cards to be able to have words and not just numbers - for example if you're playing Buzzword bingo. Perhaps what's needed here is an additional test that's designed to document how to use the code to create a realistic bingo card?

**Comment by pfichtner** [comment]
I absolutely agree and indeed that was my intention. 
Then I would try to have the test data displayed accordingly. 

```
String one = "1";
String two = "Bingo cells can contain any text";
```

So people can continue to play buzzword bingo :satisfied:
@emilybache if you agree I'd close this PR unmerged and change `one/two` data as suggested in this comment

**Comment by pfichtner** [comment]
anyone like to review, squash and merge?

**Comment by pfichtner** [comment]
Thank you Peter!

**Pull request merged**
